language: ruby
rvm:
  - 2.1.6
  - 2.2.2
addons:
  postgresql: "9.4"
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
env:
  - DATABASE_URL=postgresql://postgres@localhost/travis_ci_test
